### ISSUE TITLE
Consider adding an API?

### ISSUE THREAD

**Issue by balsama** [nstory/wokewindows#19]
Very cool project. Thanks for your work.

Have you considered adding an API? I'm curious for my own use and also to see if there are reasons you've explicitly decided not to do so.

I'm thinking that an API where I could, for example, retrieve the number of internal affairs complaints per month... or see the number of officers per neighborhood ...would be useful.

**Comment by nstory** [comment]
Thank you for reaching out!

My TL;DR thoughts on an API are "No... at least not yet." I have two points:

1. Our data model and the services we want to provide are not yet fixed -- we're still figuring out what the most important use cases for Woke Windows are going to be. Until we figure that out, I don't think it makes sense to offer an API. We would need to maintain backwards compatibility and otherwise think about how our decisions to refactor data models, drop features, etc. impact parties that consume the API. That would necessarily impair our agility at this early stage where being agile is all-important.

2. I think many of the use cases for an API can be met through data exports, which are something we are very interested in providing. We already provide a [daily database dump](https://wokewindows-data.s3.amazonaws.com/wokewindows_db.sql.gz), which you can load into a local PostgreSQL database. Soon I hope to provide more exports and in more convenient formats e.g. a CSV file containing all internal affairs cases joined with the information we have on each officer (e.g. rank, home city, salary).

Do you have an example of an integration you're considering or functionality that would be useful? Maybe it's something for which we could either create an export or work on in the Woke Windows project.

**Comment by balsama** [comment]
This makes sense. I greedily want an API just so I can poke around with scripts at the data... because it's so interesting.

But, as you point out, I could do that with a data export for now. Especially considering that I don't have a specific integration that I'm thinking of. I just want to play around.

Thanks for this work. It's invaluable.

**Comment by nstory** [comment]
Thank you for reaching out! Also, we're open to any contributions, ideas, etc. So, keep in touch!
