### ISSUE TITLE
For certain record types, navigating to URLs for records that don't exist throws 500s, not 404s

### ISSUE THREAD

**Issue by jacoblurye** [nstory/wokewindows#21]
Just for interest, I tried navigating to pages for record IDs that I know don't exist in the database. I found that doings so leads to a server error for field contacts, incidents, and IA complaints.

See, for example:
* field contacts: https://www.wokewindows.org/field_contacts/1234567
* incidents: https://www.wokewindows.org/incidents/1234567
* IA complaints: https://www.wokewindows.org/complaints/1234567

It would be better to return "404 Not Found" in these cases, as we do for other record types.

Update either the controller or the `show.html.erb` view for each of the above record types so that navigating to a non-existent record leads to a 404 error, not a 500 error.

**Comment by nstory** [comment]
Ahh, I see the problem here. I need to use [find_by!](https://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by-21) (with the bang) to look up the record. If it's not found, `find_by!` raises a `ActiveRecord::RecordNotFound` exception which ActionController will translate into a 404.

**Comment by nstory** [comment]
merged
